# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build and deploy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.1
      with:
        tokenSuffix: '}'
        files: '["**/environments/*.ts"]'
      env:
        pubkey: ${{ secrets.PUBKEY }}
        pvtkey: ${{ secrets.PVTKEY }}
        urlbase: ${{ secrets.URLBASE }}
        
    - name: Building and Deploying...
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1 
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }} 
        build_configuration: production 
        base_href: /angular-marvel-heroes-api/  
        deploy_branch: gh-pages 
        angular_dist_build_folder: dist/angular-marvel-heroes-api
  
